version: "3.8"
services:
  frontend:
    build: ./Frontend/fwas-statistics
    ports:
      - 9090:9090
  backend:
    build: ./Backend
    ports:
      - 9091:9091
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=fwas
      - DB_USER=postgres
      - DB_PASSWORD=Fwas@5775$
  database:
    build: ./database
    ports:
      - 5431:5432
    environment:
      - POSTGRES_User=fwas
      - POSTGRES_PASSWORD=Fwas@5775$
      - POSTGRES_DB=fwas